name: Run commitlint on PR

on: [pull_request]

jobs:
  run-commitlint-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # HEADからどれだけコミットを遡るかの設定
          # 0 とすれば全てのコミットを遡ることができる
          # 指定しないと Error: fatal: Invalid revision range というエラーで落ちてしまう
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # Node のバージョンは package.json に volta pin で指定したものを使用
          node-version-file: package.json
      - name: Install dependencies
        run: yarn install
      - name: Validate all commits from PR
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose